<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="description" content="Header" />
    <meta name="keywords"    content="Header" />
    <meta name="author"      content="Joshua Jasin" />
  <link href="styles/style.css" rel="stylesheet"/> 
</head>
  <div class="header">
    <header>
	    <div class="h_image">
			<a href="index.php"><img src="images/logo.png" alt="Company Logo" ></a>
</div>
