<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="description" content="Header" />
    <meta name="keywords"    content="Header" />
    <meta name="author"      content="Joshua Jasin" />
  <link href="styles/style.css" rel="stylesheet"/> 
</head>
		<div class="menu">	<nav>
    <p><a href="index.php">Home</a></p> 
		<p><a href="jobs.php">Job List</a></p> 
		<p><a href="about.php">About</a></p> 
		<p><a href="enhancements.php">Enhancements</a></p> 
                <p><a href="manage.php">PHP Enhancements</a></p> 
                <p><a href="manage.php">Admin</a></p> 
    </nav>
    </div>
		<div class="applyy">
        <p><a href="apply.php" id="applybutton">Apply</a></p>
		</div>
    </header>
