<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="description" content="Footer" />
    <meta name="keywords"    content="Footer" />
    <meta name="author"      content="nits" />
  <link href="styles/style.css" rel="stylesheet"/> 
	<div class="footer">
	<footer>
		<p>Accredited by Archery2024</p>
		<p>&#169; Archery Club</p>
		<a><p>Archer</p></a>
	</footer>
    </div>
