<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="description" content="Header" />
    <meta name="keywords"    content="Header" />
    <meta name="author"      content="Joshua Jasin" />
  <link href="styles/style.css" rel="stylesheet"/> 
	<div class="footer">
	<footer>
		<p>Accredited by ACS</p>
		<p>&#169; JNNR Company</p>
		<a href="about.html"><p>About Us</p></a>
	</footer>
    </div>